services:
  postgresql:
    image: postgres:14
    container_name: postgres14
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: applydigital
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
    container_name: api
    restart: always
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 3000
      DB_HOST: 'postgresql'
      DB_PORT: 5432
      DB_USER: 'root'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'applydigital'
      TYPEORM_TIMEZONE: 'Z'
      JWT_SECRET: 'r185stYfSHrksmID1gXlmwCQ2QRT72QRF3lf6i8zT5p7B/nAb4IY5KeAGXFQBzvZAiBZGLuuCUIguJMvzbCxutUi+SFJnhy8uoq9lSQofiEbVCWzk2JG0D3OQVTqDsXUuT02G+/2HmJbY81r6jYsc5ktu5PUhDFA6k+d78IeKwMIuEDUhFgKDCwnBYnLauRYpKO7kwoRSYbm3bBqiHDoOE96zy9HRF3K9RT2W6qYDLQIeXhVOW0D2nm5gmrrDvGdvVPK1tsstXCB4Fw3MxQPapLaQlPZlUJxxqQc6ejmix3sBas0yPy4ZIjCenMoKaSQ7Hnnn5aJC7qRHBNKcH2e7B=='
      JWT_EXPIRES_IN: '1d'
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  postgres-data:
    driver: local
  applydigital-data:
    driver: local