services:
  postgresql:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TYPEORM_TIMEZONE: ${TYPEORM_TIMEZONE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      
    ports:
      - '3000:3000'

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  applydigital-data:
    driver: local
